version: '3.8'

services:
  neo4j:
    container_name: neo4j-database
    image: 'neo4j:latest'
    environment:
      - 'NEO4J_AUTH=neo4j/notverysecret'
      - NEO4J_PLUGINS=["graph-data-science", "apoc"]
    ports:
      - '7687:7687'
      - '7474:7474'

  backend_service:
    build: ./social-network-visualizer-backend
    container_name: backend_container_inz
    ports:
      - '8080:8080'
    volumes:
      - ./social-network-visualizer-backend:/app
    depends_on:
      - neo4j

  frontend_service:
    build: ./social-network-visualizer-frontend
    container_name: frontend_container_inz
    ports:
      - '3000:3000'
    volumes:
      - ./social-network-visualizer-frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - backend_service
    environment:
      - WATCHPACK_POLLING=true
      